[build]
  command = "npm run build"
  publish = "frontend/dist"

[dev]
  command = "npm run serve"
  targetPort = 8080

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/tasks"
  status = 200
